import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Bottombanner from "@/components/bottom-banner/BottomBanner";
import TopBanner from "@/components/banner/TopBanner";
import CTABanner from "@/components/ctaBanner/CTABanner";
import Navbar from "@/components/header/Header";
import FooterCTA from "@/components/footer-cta/FooterCTA";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <TopBanner />
            <CTABanner />
            <Navbar />
            {children}
            <FooterCTA/>
            <Footer/>
            <Bottombanner />
        </>
    );
}
